#!/usr/bin/env bash
set -euo pipefail

ci_clean() {
    # Clean up our cached build layers if we're running in CI
    if [ -z "${GITHUB_RUN_ID+x}" ]; then
        echo "Not running in CI. Preserving cached build layers."
    else
        podman system prune --all --force --volumes
    fi
}

build_keygen() {
    (
        cd "$(pwd)/keygen"
        ./build.sh
        ci_clean
    )
}

build_firmware() {
    (
        cd "$(pwd)/firmware"
        ./build.sh
        ci_clean
    )
}

build_kernel() {
    (
        cd "$(pwd)/kernel"
        ./build.sh
        # We do not clean between kernel and userland build, since we
        # use the contents of the kernel container in the userland step
    )
}

build_userland() {
    (
        cd "$(pwd)/userland"
        ./build.sh
        ci_clean
    )
}

build_uki() {
    (
        cd "$(pwd)/uki"
        ./build.sh
        ci_clean
    )  
}

build_stboot() {
    (
        cd "$(pwd)/stboot"
        ./build.sh
        ci_clean
    )  
}

time build_keygen   | tee logs/build_keygen.log
time build_firmware | tee logs/build_firmware.log
time build_kernel   | tee logs/build_kernel.log
time build_userland | tee logs/build_userland.log
time build_uki      | tee logs/build_uki.log
time build_stboot   | tee logs/build_stboot.log
