#!/usr/bin/env bash
set -euo pipefail

build_keygen() {
    (
        cd "$(pwd)/keygen"
        ./build.sh
    )
}

build_kernel() {
    (
        cd "$(pwd)/kernel"
        ./build.sh
    )
}

build_userland() {
    (
        cd "$(pwd)/userland"
        ./build.sh
    )
}

build_uki() {
    (
        cd "$(pwd)/uki"
        ./build.sh
    )  
}

time build_keygen   | tee logs/build_keygen.log
time build_kernel   | tee logs/build_kernel.log
time build_userland | tee logs/build_userland.log
time build_uki      | tee logs/build_uki.log
