#!/usr/bin/env sh

# This test validates:
#   - OVMF firmware build
#   - Kernel build
#   - Initramfs build
#   - UKI build
#   - Secure Boot (using custom keys, which should pass)

# Copy Secure Boot VARS with our custom keys to temp location
cp -fv ../firmware/build/OVMF_VARS_CUSTOM.json /tmp/OVMF_VARS_CUSTOM.json

# Configure options based on system arch
. ./.archconfig

# Start a webserver to host the NekOS images
# (kill any existing ones we've still got hanging around)
kill "$(pgrep -xf 'python3 -m http.server -d ../stboot/build')"
(python3 -m http.server -d ../stboot/build)&

${qemu} \
  -m 2G \
  -cpu host \
  -machine ${machine} \
  -kernel ../stboot/build/stboot.uki.signed \
  -drive if=pflash,format=raw,unit=0,file=../firmware/build/firmware.fd,readonly=on \
  -device ${vartype},jsonfile=/tmp/OVMF_VARS_CUSTOM.json \
  -append "earlyprintk=${console} console=${console}" \
  -serial mon:stdio \
  -display ${display}
