#!/usr/bin/env sh

# This test validates:
#   - OVMF firmware build
#   - Kernel build
#   - Initramfs build

# Copy VARS to temp location
cp -fv ../firmware/build/OVMF_VARS_INSECURE.json /tmp/OVMF_VARS_INSECURE.json

# Configure options based on system arch
. ./.archconfig

# Run with OVMF CODE and VARS
${qemu} \
  -m 2G \
  -cpu host \
  -machine ${machine} \
  -kernel ../kernel/build/bzImage \
  -initrd ../userland/build/initramfs \
  -drive if=pflash,format=raw,unit=0,file=../firmware/build/OVMF_CODE.fd,readonly=on \
  -device ${vartype},jsonfile=/tmp/OVMF_VARS_INSECURE.json \
  -append "console=${console}" \
  -serial mon:stdio \
  -display ${display}
