#!/usr/bin/env sh

# This test validates:
#   - OVMF firmware build
#   - Kernel build
#   - Initramfs build
#   - UKI build
#   - Secure Boot (using custom keys, which should pass)

# Copy Secure Boot VARS with our custom keys to temp location
cp -fv ../firmware/build/OVMF_VARS_CUSTOM.json /tmp/OVMF_VARS_CUSTOM.json

# Configure options based on system arch
. ./.archconfig

# Run with custom OVMF CODE and custom VARS which contain
# our custom Secure Boot key signing chain
#
# We also specifically need to boot the UKI here since
# otherwise QEMU doesn't fully validate the Secure Boot
# state (it flashes a warning that passing the kernel
# directly is insecure)
${qemu} \
  -m 2G \
  -cpu host \
  -machine ${machine} \
  -kernel ../uki/build/uki.efi \
  -drive if=pflash,format=raw,unit=0,file=../firmware-nix/build/ovmf_img.fd,readonly=on \
  -device ${vartype},jsonfile=/tmp/OVMF_VARS_CUSTOM.json \
  -append "earlyprintk=${console} console=${console}" \
  -serial mon:stdio \
  -display ${display}
