#!/usr/bin/env sh

# This test validates:
#   - OVMF firmware build
#   - Kernel build
#   - Initramfs build
#   - UKI build

# Copy empty insecure VARS to temp location
cp -fv ../efivars/build/OVMF_VARS_INSECURE.json /tmp/OVMF_VARS_INSECURE.json

# Configure options based on system arch
. ./.archconfig

${qemu} \
  -m 2G \
  -cpu host \
  -machine ${machine} \
  -kernel ../uki/build/uki.efi \
  -drive if=pflash,format=raw,unit=0,file=../firmware/build/firmware.fd,readonly=on \
  -device ${vartype},jsonfile=/tmp/OVMF_VARS_INSECURE.json \
  -append "earlyprintk=${console} console=${console}" \
  -serial mon:stdio \
  -display ${display}
