#!/usr/bin/env sh

# This test validates:
#   - OVMF firmware build
#   - Kernel build

# Copy VARS to temp location
cp -fv ../efivars/build/OVMF_VARS_INSECURE.json /tmp/OVMF_VARS_INSECURE.json

# Configure options based on system arch
. ./.archconfig

# Run with OVMF CODE and VARS
${qemu} \
  -m 2G \
  -cpu host \
  -machine ${machine} \
  -kernel ../kernel/build/kernel \
  -drive if=pflash,format=raw,unit=0,file=../firmware/build/firmware.fd,readonly=on \
  -device ${vartype},jsonfile=/tmp/OVMF_VARS_INSECURE.json \
  -append "earlyprintk=${console} console=${console}" \
  -serial mon:stdio
