#!/usr/bin/env sh

# This test validates:
#   - Kernel build

# Configure options based on system arch
. ./.archconfig

${qemu} \
  -m 2G \
  -cpu host \
  -machine ${machine} \
  -kernel ../kernel/build/kernel \
  -append "console=tty0" \
  -serial mon:stdio
