#!/usr/bin/env sh

# This test validates:
#   - Kernel build
#   - Initramfs build

# Configure options based on system arch
. ./.archconfig

${qemu} \
  -m 2G \
  -cpu host \
  -machine ${machine} \
  -kernel ../kernel/build/bzImage \
  -initrd ../userland/build/initramfs \
  -append "console=${console}" \
  -serial mon:stdio \
  -display ${display}
